import React, { useState } from 'react';
import { Copy, Check, Download, Share2, X, FileText, Code } from 'lucide-react';
import { BenchmarkReport } from '../types';

interface ReportExportModalProps {
  report: BenchmarkReport;
  onClose: () => void;
}

export const ReportExportModal: React.FC<ReportExportModalProps> = ({ report, onClose }) => {
  const [copiedFormat, setCopiedFormat] = useState<string | null>(null);

  const generateMarkdown = () => {
    return (
      `### 🚀 LoadPulse Benchmark Report\n\n` +
      `**Target:** \`${report.url}\` | **Method:** \`${report.method}\`\n` +
      `**Concurrency:** ${report.concurrency} VUs | **Duration:** ${(report.durationActualMs / 1000).toFixed(1)}s\n\n` +
      `| Metric | Value |\n` +
      `| :--- | :--- |\n` +
      `| **Total Requests** | ${report.totalRequests.toLocaleString()} |\n` +
      `| **Successful** | ${report.successfulRequests.toLocaleString()} |\n` +
      `| **Failed / Errors** | ${report.failedRequests} |\n` +
      `| **Throughput (Mean)** | ${report.rpsMean} req/s |\n` +
      `| **Throughput (Peak)** | ${report.rpsPeak} req/s |\n` +
      `| **Latency p50 (Median)** | ${report.latencies.p50} ms |\n` +
      `| **Latency p90** | ${report.latencies.p90} ms |\n` +
      `| **Latency p95** | ${report.latencies.p95} ms |\n` +
      `| **Latency p99** | ${report.latencies.p99} ms |\n` +
      `| **Latency p99.9** | ${report.latencies.p99_9} ms |\n` +
      `| **Latency Min / Max** | ${report.latencies.min} ms / ${report.latencies.max} ms |\n\n` +
      `_Generated by [LoadPulse Cloud](https://github.com/alexandrmotologa/loadpulse-cloud) companion to [alexandrmotologa/loadpulse](https://github.com/alexandrmotologa/loadpulse)_`
    );
  };

  const copyToClipboard = (text: string, format: string) => {
    navigator.clipboard.writeText(text);
    setCopiedFormat(format);
    setTimeout(() => setCopiedFormat(null), 2000);
  };

  const downloadJson = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(report, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `loadpulse-${report.id}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fadeIn">
      <div className="glass-panel w-full max-w-lg rounded-2xl p-6 flex flex-col gap-5 border border-slate-700/80 shadow-2xl relative">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center gap-2">
          <div className="p-2 rounded-xl bg-pulse-500/10 text-pulse-400">
            <Share2 className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base font-bold text-white">Share & Export Benchmark</h3>
            <p className="text-xs text-slate-400">Export results for GitHub, documentation, or archiving</p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <button
            onClick={() => copyToClipboard(generateMarkdown(), 'markdown')}
            className="p-3 rounded-xl bg-slate-900 border border-slate-800 hover:border-pulse-500 text-left flex items-start gap-3 transition-all group"
          >
            <FileText className="w-5 h-5 text-pulse-400 mt-0.5 group-hover:scale-110 transition-transform" />
            <div>
              <div className="flex items-center gap-1.5 text-xs font-bold text-white">
                Copy Markdown Table
                {copiedFormat === 'markdown' ? (
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                ) : (
                  <Copy className="w-3.5 h-3.5 text-slate-500" />
                )}
              </div>
              <span className="text-[11px] text-slate-400 block">Formatted for GitHub PRs & issues</span>
            </div>
          </button>

          <button
            onClick={downloadJson}
            className="p-3 rounded-xl bg-slate-900 border border-slate-800 hover:border-cyan-500 text-left flex items-start gap-3 transition-all group"
          >
            <Download className="w-5 h-5 text-cyan-400 mt-0.5 group-hover:scale-110 transition-transform" />
            <div>
              <div className="flex items-center gap-1.5 text-xs font-bold text-white">
                Download JSON Data
              </div>
              <span className="text-[11px] text-slate-400 block">Complete raw histogram metrics</span>
            </div>
          </button>
        </div>

        {/* Markdown Preview */}
        <div className="flex flex-col gap-1.5">
          <label className="text-xs font-semibold text-slate-400 flex items-center gap-1">
            <Code className="w-3.5 h-3.5" /> Markdown Preview
          </label>
          <pre className="p-3 rounded-xl bg-slate-950 border border-slate-800/80 text-[11px] font-mono text-slate-300 max-h-48 overflow-y-auto whitespace-pre-wrap">
            {generateMarkdown()}
          </pre>
        </div>

        <button
          onClick={onClose}
          className="w-full py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-slate-200 transition-colors"
        >
          Close
        </button>
      </div>
    </div>
  );
};
